name: Package - Windows32

on:
  #push:
  #  branches: [ master ]

  #pull_request:
  #  branches: [ master ]

  workflow_dispatch:

  workflow_call:

jobs:
  windows32:
    name: Windows32
    runs-on: windows-latest

    env:
      MSYSTEM: mingw32

    defaults:
      run:
        shell: msys2 {0}

    steps:
      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW32
          update: true
          install: >-
            git
            zip
            mingw-w64-i686-pkgconf
            mingw-w64-i686-cmake
            mingw-w64-i686-physfs
            mingw-w64-i686-SDL
            mingw-w64-i686-SDL_mixer
            mingw-w64-i686-libpng
            mingw-w64-i686-glew
            mingw-w64-i686-ntldd-git
            mingw-w64-i686-clang
            mingw-w64-i686-lld

      - name: Clone repository
        uses: actions/checkout@v3

      - name: Configure D1
        run: CC=clang CXX=clang++ cmake -S d1 -B buildd1 -DCMAKE_BUILD_TYPE=RelWithDebInfo

      - name: Build D1
        run: cmake --build buildd1

      - name: Configure D2
        run: CC=clang CXX=clang++ cmake -S d2 -B buildd2 -DCMAKE_BUILD_TYPE=RelWithDebInfo

      - name: Build D2
        run: cmake --build buildd2

      - name: Package
        run: ./contrib/packaging/windows/build_package.sh

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows32
          path: '*.zip'
